/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import io.vertx.core.Vertx;
import org.example.controller.MainVertical;

public class App {


    public static void main(String[] args) {
        Vertx vertx= Vertx.vertx();
        vertx.deployVerticle(new MainVertical());
    }
}
